### ISSUE TITLE
Дизайн страницы личного кабинета ОУ(мобилка)

### ISSUE THREAD

**Issue by artzkh** [tomtit-tomsk/IT-cluster-platform#363]
https://www.figma.com/file/6bk1fdyFdf1JHPDH7pERYI/IT-%D0%BA%D0%BB%D0%B0%D1%81%D1%82%D0%B5%D1%80?node-id=1-13&t=akYtpbuD9x9mtFwC-0

**Comment by MrCrotplay** [comment]
Не вижу сильных косяков, я кинул в тестирование чтобы потом другие тестеры посмотрели, потому что я проблем не вижу. Ну и там комментики оставил, это кстати третья копия такого сообщения.
