### ISSUE TITLE
Дизайн страницы личного кабинета студент(мобилка)

### ISSUE THREAD

**Issue by artzkh** [tomtit-tomsk/IT-cluster-platform#364]
https://www.figma.com/file/6bk1fdyFdf1JHPDH7pERYI/IT-%D0%BA%D0%BB%D0%B0%D1%81%D1%82%D0%B5%D1%80?node-id=1-11&t=akYtpbuD9x9mtFwC-0

**Comment by IvanMonkeyTester** [comment]
добавить окна редактирования на мобилке
