### ISSUE TITLE
Добавить сообщение о подтверждении действия при отмене потребности/вакансии

### ISSUE THREAD

**Issue by artzkh** [tomtit-tomsk/IT-cluster-platform#373]
"Вы уверены, что хотите отменить потребность/вакансию?" -да/нет

**Comment by pl-al** [comment]
крестик справа бы... привычнее

![Image](https://github.com/tomtit-tomsk/IT-cluster-platform/assets/95371698/27ea883c-ad03-4de5-abb1-d74f3c4a4d26)

**Comment by IvanMonkeyTester** [comment]
А зачем тут вообще крестик
