### ISSUE TITLE
Поправить воротничок зверине на аватарке в телеграмме

### ISSUE THREAD

**Issue by IvanMonkeyTester** [tomtit-tomsk/IT-cluster-platform#537]
# Неровный воротничок на аватарке в telegram 

### Необходимо пофиксить отображение воротничка рубашки на аватарке пользователя ZVERINA1337

Ожидаемый результат | Фактический результат | Приложение
-- | -- | --
Воротничок рубашки ровный, выглаженный, симметричный | Воротничок справа не соответствует воротничку слева, отображение кривое | ![Image](https://user-images.githubusercontent.com/119807331/229686489-37ca112a-a038-4e5f-b4ad-1559296d663d.png)

**Comment by pl-al** [comment]
Good job
