### ISSUE TITLE
Кринж в вебсокете

### ISSUE THREAD

**Issue by RetmixX** [tomtit-tomsk/IT-cluster-platform#544]
Нужно привести к единому формату

![Image](https://user-images.githubusercontent.com/113033918/229711903-242d139d-375f-4c79-9b96-5b62c4d3ed47.png)

![Image](https://user-images.githubusercontent.com/113033918/229712073-916a2905-24f5-4aa0-96e4-ea3edbae23b7.png)

**Comment by Zverina1337** [comment]
норм
