### ISSUE TITLE
Добавить слайдер в активные потребности

### ISSUE THREAD

**Issue by Zverina1337** [tomtit-tomsk/IT-cluster-platform#560]
https://primevue.org/carousel/

**Comment by IvanMonkeyTester** [comment]
fanni

**Comment by IvanMonkeyTester** [comment]
Активные потребности теперь ВООБЩЕ неадаптивны 


![Image](https://user-images.githubusercontent.com/119807331/232979614-969d72e7-f7c8-4984-88bc-4691f36f750e.png)




![Image](https://user-images.githubusercontent.com/119807331/232979567-3466a89e-d6f1-4f6b-a3c3-c4f199f5a515.png)
