### ISSUE TITLE
Не получается воспроизвести

### ISSUE THREAD

**Issue by Zverina1337** [tomtit-tomsk/IT-cluster-platform#567]
Иногда переход на страницы потребностей и вакансий становится недоступен

Вывод в консоли

![Image](https://user-images.githubusercontent.com/73885381/227436744-c7308f18-9f4f-4953-ab9b-6e5b7d98bd6c.png)

Странно сгенерированный файл .js

![Image](https://user-images.githubusercontent.com/73885381/227436911-530f34a6-1edc-4ba5-99e4-f2f37135acda.png)

Раз в некоторое время при попытке перейти на вкладку вакансий или потребностей, во вкладке Network отображается тот самый странно сгенерированный файл, то в статусе 200, то в статусе 302

![Image](https://user-images.githubusercontent.com/73885381/227439839-9f7a2b62-f4f9-4880-ba51-04eb101d6ecb.png)

![Image](https://user-images.githubusercontent.com/73885381/227440090-43eb8543-a8a7-4bff-9797-2920961c82a4.png)

**Comment by acferten** [comment]
невозможно воспроизвести
