### ISSUE TITLE
Мобилка -- кривое уведомление на регистрацию студента

### ISSUE THREAD

**Issue by acferten** [tomtit-tomsk/IT-cluster-platform#571]
Уведомление об успешной регистрации студента съехало вбок
Разрешение экрана
2340 x 1080

Размеры (Основной экран)
162.1 мм (6.4") 

![Image](https://user-images.githubusercontent.com/113097599/230554828-97af83d1-df72-4196-be5e-039b5b4da280.png)

**Comment by IvanMonkeyTester** [comment]
Уведомление слишком широкое, на всю ширину экрана (на 375 даже не полностью влезает в экран)

![Image](https://user-images.githubusercontent.com/119807331/234772273-01fe61a4-fc47-4b9d-8f57-5fc4fcf6a031.png)



![Image](https://user-images.githubusercontent.com/119807331/234772530-11611fed-2b91-4372-b748-69866e7f3717.png)
