### ISSUE TITLE
Мобилка -- разный размер шрифта в подробной потребности

### ISSUE THREAD

**Issue by acferten** [tomtit-tomsk/IT-cluster-platform#572]
Не знаю, либо в дизайне так, либо только на фронте, но размер шрифта карточек потребности и информации о компании явно разный. 

![Image](https://user-images.githubusercontent.com/113097599/230555120-7adf20dc-f9b2-4c23-943e-a9b57b0aa3d7.png)

**Comment by IvanMonkeyTester** [comment]
Пофиксите везде размер шрифтов пожалуйста
