### ISSUE TITLE
Изменить ответы от апи для чата

### ISSUE THREAD

**Issue by RetmixX** [tomtit-tomsk/IT-cluster-platform#629]
Теперь в ответе возвращается дата с сервера. Так же теперь возвращается поле "avatar" у эндпоинта для получения инфы о чате

**Comment by IvanMonkeyTester** [comment]
Сотруднику должен приходить аватар студента (если студент в чате 1) 



![Image](https://user-images.githubusercontent.com/119807331/234779704-6f93024b-4c55-40fe-95ad-0e336b7b09c5.png)

Щас сотруднику приходит только аватарка компании

**Comment by RetmixX** [comment]
Жду требований для изменения чата

**Comment by RetmixX** [comment]
Переношу в сдано, так как аналитики не внесли никаких правок по чату
