### ISSUE TITLE
Переверствать подробную информацию

### ISSUE THREAD

**Issue by Zverina1337** [tomtit-tomsk/IT-cluster-platform#639]

**Comment by Sooonei** [comment]
Вакансии
https://www.figma.com/file/6bk1fdyFdf1JHPDH7pERYI/IT-%D0%BA%D0%BB%D0%B0%D1%81%D1%82%D0%B5%D1%80?node-id=449%3A556&t=ysxL2Ia142ldBUS2-1
https://www.figma.com/file/6bk1fdyFdf1JHPDH7pERYI/IT-%D0%BA%D0%BB%D0%B0%D1%81%D1%82%D0%B5%D1%80?node-id=1%3A10&t=ysxL2Ia142ldBUS2-1

Потребности
https://www.figma.com/file/6bk1fdyFdf1JHPDH7pERYI/IT-%D0%BA%D0%BB%D0%B0%D1%81%D1%82%D0%B5%D1%80?node-id=443%3A244&t=ysxL2Ia142ldBUS2-1
https://www.figma.com/file/6bk1fdyFdf1JHPDH7pERYI/IT-%D0%BA%D0%BB%D0%B0%D1%81%D1%82%D0%B5%D1%80?node-id=1%3A8&t=ysxL2Ia142ldBUS2-1

**Comment by pl-al** [comment]
От компании, вакансии


![Image](https://user-images.githubusercontent.com/95371698/236383092-61f2a5cc-b853-40b7-8edd-377dce2df795.png)
