### ISSUE TITLE
Переделать отображение специальностей в личном кабинете ОУ

### ISSUE THREAD

**Issue by KChernogrivov** [tomtit-tomsk/IT-cluster-platform#649]
Вот это в личном кабинете сотрудника ОУ меня смущает, как будто он на специальности учится.

![Image](https://user-images.githubusercontent.com/73885381/232674754-81846b7e-f7f4-4ad3-b8fd-d3af7b9993be.png)

В потребностях и вакансиях это подходит, но здесь не очень.

Как вариант — оставить всплывающее меню, но заблокать возможность выбора. Вместо выноса названия специальности подписать выпадающий список "Специальности образовательного учреждения"

![Image](https://user-images.githubusercontent.com/73885381/232675484-6ccc1058-556a-41bb-9951-0fa63e9a81ae.png)

**Comment by pl-al** [comment]
хз как тестить задачи которые еще не залиты
