### ISSUE TITLE
Ограничить поле редактирования информации в личном кабинете 10.000 символами

### ISSUE THREAD

**Issue by SofiaAgaeva12** [tomtit-tomsk/IT-cluster-platform#653]
Для поля редактирования в личном кабинете студента, сотрудников компании и ОУ.

Сейчас можно ввести в поле более 10.000 символов, никакой ошибки не появится, но обновить информацию не получится.

**Comment by IvanMonkeyTester** [comment]
Попытка написать описание больше 1к символов у студента

![Image](https://user-images.githubusercontent.com/119807331/232969930-f5221e8b-5f0d-4986-aa52-fe85bba7c5ee.png)

Попытка написать описание больше 1к символов у ОУ

![Image](https://user-images.githubusercontent.com/119807331/232970541-cbe1f13c-6ca8-440a-9d9e-e9096097ba46.png)

У компании 

![Image](https://user-images.githubusercontent.com/119807331/232970649-55b28a19-f3e4-48ed-97e0-e382b85038ce.png)
