### ISSUE TITLE
Нет адреса на странице подробной инфы

### ISSUE THREAD

**Issue by acferten** [tomtit-tomsk/IT-cluster-platform#674]
В правой карточке компании должен отображаться адрес 

![Image](https://user-images.githubusercontent.com/119807331/231655211-d1800cdb-0181-45b9-9c8b-95626eaa3a79.png)

**Comment by pl-al** [comment]
адреса нигде не вижу

![Image](https://user-images.githubusercontent.com/95371698/234279786-5ca4f8bb-24d2-4fc0-bde0-3ba5f036604b.png)

вы либо залитые кидайте задачи, либо помечайте как-то, как это тестировать

**Comment by KChernogrivov** [comment]
Был заменен текст адрес на текст контакты.
Сейчас же дизайн обновлен и эту задачу можно считать неактуальной
