### ISSUE TITLE
Уменьшить размер шрифта названию специальности при создании вакансии/потребности

### ISSUE THREAD

**Issue by acferten** [tomtit-tomsk/IT-cluster-platform#680]
Название специальности не вмещается в поле, серая обводка обрезается снизу

![Image](https://user-images.githubusercontent.com/119807331/231640082-41e95a0b-5229-44b6-9333-6c701c64b123.png)

**Comment by IvanMonkeyTester** [comment]
Если название специальности не влезает полностью, не отображается крестик отмены, но он должен быть всегда


![Image](https://user-images.githubusercontent.com/119807331/235571650-a80308f1-5762-486a-9b8e-f16a9faf6196.png)
