### ISSUE TITLE
Переписать проект с использованием graphql

### ISSUE THREAD

**Issue by acferten** [tomtit-tomsk/IT-cluster-platform#698]
GraphQL — язык запросов данных и язык манипулирования данными с открытым исходным кодом для построения веб ориентированных программных интерфейсов. GraphQL был разработан как внутренний проект компании Facebook в 2012 году, а позднее в 2015 году был выпущен публично.
Используется в github, twitter, pinterest, The New York Times, paypal, а мы чем хуже? Переделываем.

**Comment by KChernogrivov** [comment]
https://habr.com/ru/companies/ruvds/articles/445268/
