### ISSUE TITLE
Восстановление пароля

### ISSUE THREAD

**Issue by Sooonei** [tomtit-tomsk/IT-cluster-platform#714]

**Comment by Sooonei** [comment]
https://www.figma.com/file/6bk1fdyFdf1JHPDH7pERYI/IT-%D0%BA%D0%BB%D0%B0%D1%81%D1%82%D0%B5%D1%80?node-id=664%3A253&t=8zrqQ14KttQtZ5ow-1

**Comment by pl-al** [comment]
- [ ] Опечатку пофиксить

![Image](https://user-images.githubusercontent.com/95371698/236114614-1e925285-12c9-4725-a012-6eed1b938d66.png)

- [ ] Добавить страницу самого восстановления

![Image](https://user-images.githubusercontent.com/95371698/236114657-f23d7953-415c-4309-99c6-3e85422a4ed7.png)
