### ISSUE TITLE
Интегрировать список уведомлений во всех ЛК на фронте

### ISSUE THREAD

**Issue by acferten** [tomtit-tomsk/IT-cluster-platform#749]
**Postman:** уведомления -> список уведомлений и прочитать уведомления (один GET, один PATCH)
**Дизайн:** https://www.figma.com/file/6bk1fdyFdf1JHPDH7pERYI/IT-%D0%BA%D0%BB%D0%B0%D1%81%D1%82%D0%B5%D1%80?type=design&node-id=1-25132&t=PpKgV8ZRZfeUxioF-0

**Comment by pl-al** [comment]
| **Список** | **Прочитать**
-- | -- | --
Студент | ✅ | ❌
