### ISSUE TITLE
Сделать специальности в списке некликабельными

### ISSUE THREAD

**Issue by SofiaAgaeva12** [tomtit-tomsk/IT-cluster-platform#757]
Специальности не должны быть кликабельны 

![Image](https://user-images.githubusercontent.com/119807331/235836714-e13d7da8-c5f8-442a-a812-76e770e599dd.png)

![Image](https://user-images.githubusercontent.com/119807331/235836778-6824854f-3744-40e5-ac59-b83a98d52d84.png)

**Comment by pl-al** [comment]
1. Личный кабинет сотрудника ОУ - ✅
2. Список потребностей - ❌
3. Список вакансий - ❌
4. Подробная информация (потребность/вакансия) - ❌

Например, список потребностей:

До | Выбор | После
-- | -- | --
![Image](https://github.com/tomtit-tomsk/IT-cluster-platform/assets/95371698/5891b9f5-e606-4b12-a94c-492b31049b6e) | ![Image](https://github.com/tomtit-tomsk/IT-cluster-platform/assets/95371698/84da7357-6a8e-47a1-9434-81d33262f593) | ![Image](https://github.com/tomtit-tomsk/IT-cluster-platform/assets/95371698/e91a73dc-7595-4570-a449-07f7d664c4db)
