### ISSUE TITLE
Добавить на backend возвращение 1 страницы pdf файла в jpeg

### ISSUE THREAD

**Issue by RetmixX** [tomtit-tomsk/IT-cluster-platform#790]
Реализовать код для парсинга первой страницы PDF в jpeg во время загрузки достижения, с сохраненим в базу данных, чтобы каждый раз при отдаче достижений не производить парсинг pdf документа

**Comment by IvanMonkeyTester** [comment]
Превьюшки багаются и становятся черными

![Image](https://github.com/tomtit-tomsk/IT-cluster-platform/assets/119807331/0b1e118f-70f5-4394-877a-af49c778d387)
